name: Run Gradle on PRs
on:
  push:
    branches: [ jemalloc]
jobs:
    iterations:
      name: Generate versions
      runs-on: ubuntu-latest
      steps:
         - id: calculate_iterations
           run: |
            iterations=" ["
            for i in {1..2}
            do
              if [ $i == 1 ]
              then
                iterations="$iterations \"$i\""
              else
                iterations="$iterations  , \"$i\""
              fi
            done
            iterations="$iterations ]"
            echo "iterations=$iterations" >> $GITHUB_OUTPUT
            echo $GITHUB_OUTPUT
      outputs:
         iterations: ${{ steps.calculate_iterations.outputs.iterations }}
    execution:
      needs: [iterations]
      strategy:
        matrix:
          variant: ["cdsap/android-builder:0.3","cdsap/android-builder-jemalloc:0.4"]
          runs:   ${{ fromJson(needs.iterations.outputs.iterations) }}
      runs-on: ubuntu-latest
      container:
        image: ${{ matrix.variant }}
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-java@v3
          with:
             distribution: temurin
             java-version: 17
        - uses: catchpoint/workflow-telemetry-action@v1
          with:
              proc_trace_table_show: true
        - name: Run a command inside the Docker container
          run: |
            echo $LD_PRELOAD
            echo $HOME
            ./gradlew assembleRelease -Dscan.tag.${{github.run_number}}  -Dscan.tag.${{ matrix.variant }} -Dscan.tag.experiment
          env:
            GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GE_API_KEY }}
